import { Shop } from '@/types/shop';

export const mockShops: Shop[] = [
  {
    id: '1',
    name: '焼肉 炭火屋',
    category: '韓国',
    area: '渋谷',
    address: '東京都渋谷区道玄坂1-2-3',
    budget: '¥3,000-5,000',
    rating: 4,
    memo: 'お肉が柔らかくて美味しい！ランチもコスパ◎',
    visitCount: 3,
    lastVisitDate: '2026-03-10',
    googleMapsUrl: 'https://maps.google.com/?q=渋谷+焼肉',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '2',
    name: 'パスタ・ラ・ボッカ',
    category: 'イタリアン',
    area: '表参道',
    address: '東京都港区北青山3-1-5',
    budget: '¥3,000-5,000',
    rating: 5,
    memo: '本格イタリアン！パスタが絶品',
    visitCount: 2,
    lastVisitDate: '2026-02-28',
    googleMapsUrl: 'https://maps.google.com/?q=表参道+パスタ',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '3',
    name: '中華料理 龍華',
    category: '中華',
    area: '新宿',
    address: '東京都新宿区歌舞伎町1-5-10',
    budget: '¥1,000-3,000',
    rating: 4,
    memo: '餃子が美味しい。量も多い',
    visitCount: 5,
    lastVisitDate: '2026-03-15',
    googleMapsUrl: 'https://maps.google.com/?q=新宿+中華',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '4',
    name: '寿司 魚心',
    category: '和食',
    area: '銀座',
    address: '東京都中央区銀座5-8-1',
    budget: '¥5,000-10,000',
    rating: 5,
    memo: 'ネタが新鮮！特別な日に',
    visitCount: 1,
    lastVisitDate: '2026-01-20',
    googleMapsUrl: 'https://maps.google.com/?q=銀座+寿司',
    timeSlots: ['ディナー'],
  },
  {
    id: '5',
    name: 'ビストロ・マルシェ',
    category: '洋食',
    area: '六本木',
    address: '東京都港区六本木6-1-20',
    budget: '¥5,000-10,000',
    rating: 4,
    memo: '落ち着いた雰囲気。デートに最適',
    visitCount: 2,
    lastVisitDate: '2026-02-14',
    googleMapsUrl: 'https://maps.google.com/?q=六本木+ビストロ',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '6',
    name: '天ぷら てんや',
    category: '和食',
    area: '池袋',
    address: '東京都豊島区南池袋1-28-2',
    budget: '~¥1,000',
    rating: 3,
    memo: '手軽に天ぷらが食べられる',
    visitCount: 8,
    lastVisitDate: '2026-03-18',
    googleMapsUrl: 'https://maps.google.com/?q=池袋+天ぷら',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '7',
    name: 'タコス・メキシコ',
    category: 'その他',
    area: '渋谷',
    address: '東京都渋谷区神泉町10-5',
    budget: '¥1,000-3,000',
    rating: 4,
    memo: '本格メキシコ料理！マルガリータも◎',
    visitCount: 1,
    lastVisitDate: null,
    googleMapsUrl: 'https://maps.google.com/?q=渋谷+タコス',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '8',
    name: '韓国冷麺 ヨピョン',
    category: '韓国',
    area: '新宿',
    address: '東京都新宿区百人町1-10-5',
    budget: '¥1,000-3,000',
    rating: 4,
    memo: '冷麺が最高！夏にぴったり',
    visitCount: 4,
    lastVisitDate: '2026-03-01',
    googleMapsUrl: 'https://maps.google.com/?q=新宿+冷麺',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '9',
    name: 'ピッツェリア・ナポリ',
    category: 'イタリアン',
    area: '銀座',
    address: '東京都中央区銀座8-5-10',
    budget: '¥3,000-5,000',
    rating: 5,
    memo: '窯焼きピザが本格的！',
    visitCount: 3,
    lastVisitDate: '2026-02-20',
    googleMapsUrl: 'https://maps.google.com/?q=銀座+ピザ',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '10',
    name: '洋食 キッチン・ココ',
    category: '洋食',
    area: '表参道',
    address: '東京都港区南青山5-2-8',
    budget: '¥1,000-3,000',
    rating: 3,
    memo: 'ハンバーグが人気',
    visitCount: 6,
    lastVisitDate: '2026-03-12',
    googleMapsUrl: 'https://maps.google.com/?q=表参道+洋食',
    timeSlots: ['ランチ', 'ディナー'],
  },
  {
    id: '11',
    name: '居酒屋 魚民',
    category: '和食',
    area: '渋谷',
    address: '東京都渋谷区宇田川町10-5',
    budget: '¥3,000-5,000',
    rating: 4,
    memo: '飲み会に最適',
    visitCount: 2,
    lastVisitDate: '2026-03-05',
    googleMapsUrl: 'https://maps.google.com/?q=渋谷+居酒屋',
    timeSlots: ['ディナー'],
  },
  {
    id: '12',
    name: 'ラーメン 一蘭',
    category: 'その他',
    area: '新宿',
    address: '東京都新宿区歌舞伎町2-5-10',
    budget: '~¥1,000',
    rating: 4,
    memo: '博多ラーメン！一人で食べやすい',
    visitCount: 10,
    lastVisitDate: '2026-03-20',
    googleMapsUrl: 'https://maps.google.com/?q=新宿+ラーメン',
    timeSlots: ['ランチ', 'ディナー'],
  },
];

export const categories = ['和食', '洋食', '中華', 'イタリアン', '韓国', 'その他'] as const;
export const areas = ['渋谷', '新宿', '池袋', '銀座', '六本木', '表参道', 'その他'] as const;
export const budgets = ['~¥1,000', '¥1,000-3,000', '¥3,000-5,000', '¥5,000-10,000', '¥10,000~'] as const;
export const timeSlots = ['ランチ', 'ディナー'] as const;
